List<Map<String, dynamic>> allergic = [
  {'name': "Alcohol-Cocktail", 'selected': false},
  {'name': "Alcohol-Free", 'selected': false},
  {'name': "Celery-Free", 'selected': false},
  {'name': "Crustacean-Free", 'selected': false},
  {'name': "Dairy-Free", 'selected': false},
  {'name': "DASH", 'selected': false},
  {'name': "Egg-Free", 'selected': false},
  {'name': "Fish-Free", 'selected': false},
  {'name': "FODMAP-Free", 'selected': false},
  {'name': "Gluten-Free", 'selected': false},
  {'name': "Immuno-Supportive", 'selected': false},
  {'name': "Keto-Friendly", 'selected': false},
  {'name': "Kidney-Friendly", 'selected': false},
  {'name': "Kosher", 'selected': false},
];
